include colors.conf

cursor_shape block
cursor_blink_interval 0
cursor_trail 1
cursor_trail_decay 0.1 0.4
shell_integration no-cursor
cursor_trail_start_threshold 2

window_padding_width 6
confirm_os_window_close 0
remember_window_size yes
initial_window_width 110c
initial_window_height 32c
resize_in_steps no

scrollback_lines 2000
scrollbar hovered
scrollbar_interactive no
scrollbar_hover_width 1
scrollbar_handle_opacity 0.0
scrollbar_radius 0.3
scrollbar_gap 0.1
scrollbar_min_handle_height 1
scrollbar_hitbox_expansion 0.25
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0.0
pixel_scroll yes

mouse_hide_wait 1.0

open_url_with default
url_style curly
detect_urls yes
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
show_hyperlink_targets no
underline_hyperlinks hover

click_interval 0.5
copy_on_select no
map ctrl+shift+c        copy_to_clipboard
map ctrl+shift+v        paste_from_clipboard
map ctrl+shift+k,          load_config_file
enable_audio_bell no

sync_to_monitor yes
repaint_delay 10
input_delay 3

background_blur 1
background_opacity 0.4

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 2

# new tab
map ctrl+shift+enter new_tab

# close tab
map ctrl+shift+w close_tab

# next/previous tab
map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab

# split windows
map ctrl+shift+s launch --location=hsplit

# navigate splits
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right

# font size control
map ctrl+shift+equal change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0
map ctrl+shift+backspace change_font_size all 0

# Run pfetch
shell sh -c "pfetch; exec $SHELL"
